### ISSUE TITLE
tagstream-conduit-0.5.5.3 fails to build with xml-conduit-1.9.1.1

### ISSUE THREAD

**Issue by juhp** [yihuang/tagstream-conduit#24]
At least with ghc-8.2 tagstream-conduit-0.5.5.3 [fails](https://github.com/juhp/http-directory/runs/4471384070) to build with xml-conduit-1.9.1.1.

I recommend adding a Hackage revision adding an upperbound `xml-conduit < 1.9` for tagstream-conduit-0.5.5.3.
At least I confirmed that _then_ it [builds](https://github.com/juhp/http-directory/runs/4472557656).

**Comment by yihuang** [comment]
thanks for the notice, fixed in 0.5.5.4, closing now, feel free to reopen if it's not fixed.

**Comment by juhp** [comment]
Thanks
